### ISSUE TITLE
publish to homebrew

### ISSUE THREAD

**Issue by jessfraz** [KittyCAD/cli#17]

**Comment by hanbollar** [comment]
switching to kurt for q4 priority

**Comment by hanbollar** [comment]
@jessfraz - just to clarify, this is for the cli right?

**Comment by jessfraz** [comment]
YesOn Oct 19, 2022, at 3:31 PM, Hannah Bollar ***@***.***> wrote:﻿
@jessfraz - just to clarify, this is for the cli right?

**Comment by Irev-Dev** [comment]
I had made a start in #177 to make a 'Tap', but since realised we want this publish to homebrew core, I think some of that work might still be useful though as it seems like a first step is making the binary available a `tar.gz`.

useful links:
cookbook https://docs.brew.sh/Formula-Cookbook#grab-the-url
more homebrew docs https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md#to-add-a-new-formula-for-foo-version-234-from-url
might be a easy example to follow https://github.com/RustScan/RustScan/issues/59

**Comment by Irev-Dev** [comment]
Got this PR up to homebrew atm https://github.com/Homebrew/homebrew-core/pull/117702

**Comment by Irev-Dev** [comment]
The PR above got rejected on "notability", it shouldn't be much work to shuffle things around and get this working as a "Tap".
